spring.application.name=short-url

# Render / Fly / Cloud friendly port
server.port=${PORT:8080}

# ===============================
# PostgreSQL (Render DB)
# ===============================
spring.datasource.url=postgresql://short_url_db_2q0g_user:FJMxwKkjQQJqj8qS2cN4u4k2wD6DYuhE@dpg-d6df8ap4tr6s73cpgapg-a/short_url_db_2q0g
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# ===============================
# Redis (OPTIONAL – disable for now)
# ===============================
spring.redis.enabled=false
